name = "usurai"
type = "javascript"
zone_id = ""
account_id = "e800d9852cf9648c351610aa80501788"
route = ""
workers_dev = true
compatibility_date = "2022-01-26"

kv_namespaces = [
  { binding = "KV", id = "8482f22281a94e48a3da3c6ee87168aa", preview_id = "060768c26fd24b2b837a9062066bd903" }
]

[build]
command = "yarn build"

[build.upload]
format = "service-worker"

[site]
bucket = "./frontend/build"
entry-point = "."
