name: Test

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.5.1

      - run: |
          yarn install
          cd frontend && yarn install

      - run: |
          yarn test

